declare module 'virtual:pwa-register' {
  /**
   * Minimal type declaration for `virtual:pwa-register` generated by `vite-plugin-pwa`.
   * We use `any` for options/return value to avoid strict typing issues.
   */
  export function registerSW(options?: any): any;
  const _default: typeof registerSW;
  export default _default;
}
